name: build-page
on:
  push:
    paths-ignore:
      - 'README.md'
    branches-ignore:
      - 'gh-pages'
jobs:
  run-pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - run: ./compile.sh -o
      - uses: actions/upload-artifact@v2.2.4
        with:
          name: HTML
          path: index.html
          retention-days: 1
  github-pages:
    runs-on: ubuntu-latest
    needs: [run-pandoc]
    if: ${{ success() && github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v2.3.5
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v2.0.10
        with:
          name: HTML
      - run: |
          git config --global user.name "Github Actions"
          git config --global user.email 'bluezio@users.noreply.github.com'
          git fetch origin master
          git checkout origin/master .
          git reset
          git checkout .gitignore
          git add --all .
          git diff-index --quiet HEAD || (git commit -am "Website rebuild"; git push -f)
